#!/usr/bin/env node
// Generates src/system/bundledPrompts.ts from the prompts/ tree, so a compiled
// single-file binary (which has no prompts/ dir on disk) still ships the full
// layered system prompt. In dev (node + prompts/ on disk) resolveSystem prefers
// the on-disk files, so this only kicks in for the binary. Re-run after editing
// any prompt: `node scripts/embed-prompts.mjs` (also runs in build:binary).
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const promptsDir = join(root, 'prompts');
const outFile = join(root, 'src', 'system', 'bundledPrompts.ts');

/** Recursively collect every *.md under prompts/, keyed by path relative to prompts/. */
function walk(dir) {
  const out = {};
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) Object.assign(out, walk(p));
    else if (name.endsWith('.md')) out[relative(promptsDir, p).split('\\').join('/')] = readFileSync(p, 'utf8');
  }
  return out;
}

const map = walk(promptsDir);
const entries = Object.keys(map)
  .sort()
  .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
  .join('\n');

const banner = `// AUTO-GENERATED by scripts/embed-prompts.mjs — do not edit by hand.\n// Embeds prompts/*.md so the compiled binary ships the full system prompt.\n`;
writeFileSync(outFile, `${banner}export const BUNDLED_PROMPTS: Record<string, string> = {\n${entries}\n};\n`);
console.error(`embed-prompts: wrote ${Object.keys(map).length} files → ${relative(root, outFile)}`);
