#!/usr/bin/env node
// Generates src/web/bundledAssets.ts from the src/web/ui/ source tree, so a compiled
// single-file binary (which has no src/ on disk) still ships the web UI. In dev
// (node + source on disk) the server prefers the on-disk files for hot reload; in the
// binary it falls back to this map. Re-run after editing any web UI source:
//   node scripts/embed-webui.mjs   (also runs in build:binary)
//
// Mirrors scripts/embed-prompts.mjs deliberately — same codegen pattern, runtime-agnostic,
// compiles under both tsc (→ Node) and bun build --compile. Do NOT switch to Bun's
// `import "./index.html"` — it breaks tsc and the dual-build invariant.
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const uiDir = join(root, 'src', 'web', 'ui');
const outFile = join(root, 'src', 'web', 'bundledAssets.ts');

/** Recursively collect every file under src/web/ui/, keyed by POSIX-relative path. */
function walk(dir) {
  const out = {};
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) Object.assign(out, walk(p));
    else out[relative(uiDir, p).split(sep).join('/')] = readFileSync(p, 'utf8');
  }
  return out;
}

const map = walk(uiDir);
const entries = Object.keys(map)
  .sort()
  .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
  .join('\n');

const banner =
  '// AUTO-GENERATED by scripts/embed-webui.mjs — do not edit by hand.\n' +
  '// Embeds src/web/ui/* so the compiled binary ships the web UI.\n' +
  '// Dev (on-disk files) takes precedence in src/web/assets.ts; this map is the binary fallback.\n';
writeFileSync(
  outFile,
  // Object.create(null): a plain literal inherits Object.prototype, so a lookup of '__proto__'
  // (or any inherited key) returns a non-string. assets.ts guards too; this removes the class.
  `${banner}export const BUNDLED_WEB_ASSETS: Record<string, string> = Object.assign(Object.create(null), {\n${entries}\n});\n`,
);
console.error(`embed-webui: wrote ${Object.keys(map).length} files → ${relative(root, outFile)}`);
